### ISSUE TITLE
Seria legal esse projeto ser Português

### ISSUE THREAD

**Issue by Camilotk** [lunaperegrina/awesome-bsky#23]
Existem já diversos projetos com mantenedores ativos mantendo Awesome Lists de apps para BSKY.

Alguns exemplos são:
- [notjuliet](https://github.com/notjuliet)/[awesome-bluesky](https://github.com/notjuliet/awesome-bluesky)
- [fishttp](https://github.com/fishttp)/[awesome-bluesky](https://github.com/fishttp/awesome-bluesky)

O que esse repositório tem de único e muito bacana é que ele também agrega os projetos feitos por brasileiros, muitos deles nem sempre com mais idiomas que português. Porém, a maior parte da população brasileira não fala inglês, é estimado que o número de pessoas que fala inglês é em torno de 8% ~ 15% e mesmo dentro da Comunidade de Tecnologia essa é uma barreira considerável, esses anos na http://ulivre.dev estive em contato com uma quantidade considerável de DEVs que não sabem inglês e precisam de conteúdos traduzidos para ter acesso.

Seria legal se Português fosse a linguagem oficial do Repo e ele focasse em trazer os projetos Brasil + Mundo.

Fica a sugestão.

Se precisar de ajuda com isso pode me chamar na DM do Bluesky ou Discord.

**Comment by JoaquimCassano** [comment]
Seria legal. Inclusive, daria pra criar uma aba no readme que importe os projectos do bsky-awesome gringo e atualize com uma github action

**Comment by lunaperegrina** [comment]
@JoaquimCassano essa ideia do GitHub action foi muito boa, mas como faríamos as traduções? (e acho que inicialmente poderia ser ao contrário: primeiro adiciona no arquivo BR e e depois passa pro ENG)

**Comment by lunaperegrina** [comment]
@JoaquimCassano @Camilotk  Vamos continuar essa conversa na issue https://github.com/lunaperegrina/awesome-bsky/issues/28, já que o projeto foi colocado como padrão em português
