### ISSUE TITLE
Salvar link bot

### ISSUE THREAD

**Issue by Cristuker** [lunaperegrina/awesome-bsky#4]
Criei um bot para salvar links no chat para lembrar de ler depois logo que não tenho os itens local. Atualmente ele demora um pouco pra mandar pois ainda sim to usando plano free e as vezes rodando local quando tem muita coisa.

Perfil do bot: https://bsky.app/profile/savetoread.bsky.social
Github: https://github.com/Cristuker/save-to-later

**Comment by lunaperegrina** [comment]
Sinta-se a vontade pra abrir a PR e definir como vc quer deixar os links, tanto para o bot quanto para o seu perfil :D (se quer usar o GitHub, bluesky ou ate mesmo um linktree para o seu perfil!)

**Comment by Cristuker** [comment]
Pra já capitão
